version: '3'
services:
  mysql-master:
    image: mysql:8.0.16
    container_name: mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
      - privileged:true
    volumes:
      - /app/data/mysql/master/log:/var/log/mysql
      - /app/data/mysql/master/data:/var/lib/mysql
      - /app/data/mysql/master/conf:/etc/mysql
    networks:
      - mysql-net
    ports:
      - "6001:3306"
  mysql-slave:
    image: mysql:8.0.16
    container_name: mysql-slave
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /app/data/mysql/slave/log:/var/log/mysql
      - /app/data/mysql/slave/data:/var/lib/mysql
      - /app/data/mysql/slave/conf:/etc/mysql
    depends_on:
      - mysql-master
    networks:
      - mysql-net
    ports:
      - "6002:3306"
networks:
  mysql-net: